spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/vitamate
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
#---
#spring:
#  config:
#    activate:
#      on-profile: develop
#  datasource:
#    url: ${AWS_DB_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${AWS_DB_USERNAME}
#    password: ${AWS_DB_PASSWORD}
#  sql:
#    init:
#      mode: never
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: create
#        default_batch_fetch_size: 1000

#  servlet:
#    multipart:
#      enabled: true
#      maxFileSize: 100MB
#      maxRequestSize: 300MB

#---
#spring:
#  config:
#    activate:
#      on-profile: release
#  datasource:
#    url: ${aws.db.url}
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${aws.db.username}
#    password: ${aws.db.password}
#  sql:
#    init:
#      mode: never
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: create
#        default_batch_fetch_size: 1000
