spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vitamate
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000