# default
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/vitamate
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jwt:
    secret: ${JWT_SECRET}

api:
  key: ${API_KEY}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${RDS_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_DB_USERNAME}
    password: ${RDS_DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

#  servlet:
#    multipart:
#      enabled: true
#      maxFileSize: 100MB
#      maxRequestSize: 300MB

#---
#spring:
#  config:
#    activate:
#      on-profile: release
#  datasource:
#    url: ${aws.db.url}
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${aws.db.username}
#    password: ${aws.db.password}
#  sql:
#    init:
#      mode: never
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: create
#        default_batch_fetch_size: 1000
